[tool.bumpver]
current_version = "1.1.1"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit = false
tag = false
push = false

[tool.bumpver.file_patterns]
"Makefile" = ["PACKAGE_VERSION?={version}"]
"pyproject.toml" = ['version = "{version}"']
"uv.lock" = ['version = "{version}"']
"koyeb/*.md" = ["Package version: {version}"]
"koyeb/__init__.py" = ['__version__ = "{version}"']
"koyeb/api/__init__.py" = ['__version__ = "{version}"']
"koyeb/api/api_client.py" = ['OpenAPI-Generator/{version}']
"koyeb/api/configuration.py" = ['SDK Package Version: {version}']
"koyeb/sandbox/__init__.py" = ['__version__ = "{version}"']
